import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Banner from "@/components/layout/banner";
import Footer from "@/components/layout/footer";

const inter = Inter({subsets:["latin"], variable:"--font-inter"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Banner/>
        <Navbar/>
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
